### PR TITLE
First version of Turbina

### PR DESCRIPTION
**Pull request by lukasedw**
## Status

* (WIP, Ready, Needs Review)

## Additional Notes

This plugin will make available turbo streams. When all looks good i will make the documentation and tests.

### CODE REVIEW

**Comment by ParamagicDev** [comment]
I have a feeling this could be heavily simplified. In fact I've been curious about simplifying the cableready plugin as well but havent had time.

My initial thoughts are it feels weird to introduce a new data attribute for turbo instead of users just doing: `data-turbo="true"`

the other thing is I think we could just change default mimetypes for a plugin. I think the isTurboResponse and auto processing it is awesome.

**Comment by leastbad** [comment]
I am confused as to the use case for this mechanism. Could you walk through a code path or scenario for why this would be useful?

TIA!

**Comment by lukasedw** [comment]
> I have a feeling this could be heavily simplified. In fact I've been curious about simplifying the cableready plugin as well but havent had time.
> 
> My initial thoughts are it feels weird to introduce a new data attribute for turbo instead of users just doing: `data-turbo="true"`
> 
> the other thing is I think we could just change default mimetypes for a plugin. I think the isTurboResponse and auto processing it is awesome.

I think this too, but do you think its fine for a first version?
I didn't use `data-turbo="true"` because the documentation warns not to use it. What are the implications of having it?
I thought about it too, but i just follow the pattern of the cable ready. What i did before was just add turbo-streams headers on headers.ts

**Comment by leastbad** [comment]
I appreciate your enthusiasm, but "fine for a first version" isn't going to cut it for actually shipping... although perhaps I am misunderstanding your qualifier.

A video would be super helpful!

Let me better explain: I don't fully understand why you need Turbo Stream support in mrujs, since the way TS works is via custom web components that don't care how they were added to the page. Can't you just return HTML normally that just happens to include TS elements? It doesn't seem like it's something mrujs needs to "support" since it should already just work.

We really care a lot about the API surface for this and I know that we're both pretty confused by the big picture idea of this. It's not the "how" so much as the "why".

**Comment by lukasedw** [comment]
@leastbad it is almost the case of CableCar, to facilitate the thigs, if i want to use in 10 form, then dont need to work with callbacks and other things, Turbina already handles everything.

Video: [https://www.youtube.com/watch?v=Vu-eL30tnxU](https://www.youtube.com/watch?v=Vu-eL30tnxU)

**Comment by leastbad** [comment]
I need you to answer my question. Turbo Stream is just web components in an HTML fragment. Why does mrujs need to do anything other than just update HTML?

CableReady/CableCar is JSON. It needs to be interpreted. That's the difference!

**Comment by lukasedw** [comment]
But I think I already answered you, i see this plugin more like a helper, instead of doing this by yourself, this plugin do it for you.

**Pull request closed without merging**
