### PR TITLE
Add morphdom by id

### PR DESCRIPTION
**Pull request by lukasedw**
## Status

* (WIP, Ready, Needs Review)

## Additional Notes

This enable to select which element will be replaced by morphdom using "data-morphdom-id". If all looks good i will make the documentation and tests.

### CODE REVIEW

**Comment by leastbad** [comment]
Is there a specific reason this has to be tied to an id instead of a CSS selector?

**Comment by lukasedw** [comment]
> Is there a specific reason this has to be tied to an id instead of a CSS selector?

If was a CSS selector, that means morphdom could be looking for multiple elements, and i think thats not the case for it.

**Comment by ParamagicDev** [comment]
> > Is there a specific reason this has to be tied to an id instead of a CSS selector?
> 
> If was a CSS selector, that means morphdom could be looking for multiple elements, and i think thats not the case for it.

This is absolutely the case. I dont want to morph only the form that submitted, there may be other things that trigger and i want to morph the full page. If someone needs more fine-grained functionality, mrujs is not the place for it.

**Comment by lukasedw** [comment]
But morphing the entire page can lead to some problems with some js, specifying the morph can be very helpful, i think there is plenty of use case for this.

**Comment by ParamagicDev** [comment]
@lukasedw so basically like a `data-reflex-root` in StimulusReflex?

**Comment by leastbad** [comment]
It really sounds like you're trying to turn mrujs into StimulusReflex, which is very not the road map for mrujs.

On the positive side, it sounds like you'd love StimulusReflex: https://docs.stimulusreflex.com/rtfm/morph-modes#scoping-page-morphs

**Comment by lukasedw** [comment]
@ParamagicDev yes, that will work like that, @leastbad i dont agree with you, one of the greatest things about mrujs is the validations that can be easily brought to the view with morphdom, i cannot do this with stimulus reflex just by adding one tag...the whole point is the mrujs facilitate and innovate at some points.

**Comment by leastbad** [comment]
I'm not sure I understand what you're trying to do, perhaps. A moment ago you agreed that it would work like `data-reflex-root`.

mrujs isn't trying to reinvent the wheel. We're actively trying to keep the API surface tight and compact.

**Comment by ParamagicDev** [comment]
@lukasedw The navigation adapter is admittedly quite dense with a number of conditional routes and I fear this will introduce additional complexity when debugging. 

Perhaps this could live as a mrujs plugin that you create in a third party package? I dont see myself supporting this, but this could definitely live as a plugin that hooks into `ajax:complete` and checks for the existence of the `data-morph-id` and then cancels navigation and does its thing.

As @leastbad im not trying to reinvent the wheel. Thats part of the reason for the plugin system is to allow for users to adjust for their personal edge cases.

**Comment by lukasedw** [comment]
Ok, i understand, i will do that, thanks a lot for your time! @leastbad @ParamagicDev

**Pull request closed without merging**
